#!/usr/bin/env python3
"""Validate that all bare mentions of known technologies are wiki-links.

Reads the technology list from meta/canonical-map.json (generated by
meta/scripts/generate-canonical-map.py).  For each .md file in patterns/
and tools/ (excluding tools/ directory ONLY when scanning patterns/ and
vice-versa — though both need checking), finds all occurrences of each
technology display name that are NOT already a wiki link [...](canonical-path).

False-positive exclusions:
  - Lines containing '[' (already a markdown link somewhere — heuristic)
  - Lines starting with '**X**:'  (bullet integration lists, e.g. '**LlamaIndex**:')
  - URL-path-like text:  'something.something/api/anthropic' (e.g. api.z.ai/api/anthropic)
  - Lines where the bare mention appears inside an inline-code span (`...`)
  - The word "Opus" when not preceded by "Claude " (common English word)
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
MAP_PATH = ROOT / "meta" / "canonical-map.json"

SCAN_DIRS = [ROOT / "patterns", ROOT / "tools"]
# Always exclude the scan dirs themselves + meta + sources + assets
EXCLUDE_PREFIXES = (ROOT / "meta", ROOT / "sources", ROOT / "assets", ROOT / ".git")

# ── known ambiguous short words that need extra context ──
AMBIGUOUS = frozenset({"BGE"})  # homonym / too short

# ── load canonical map ──


def load_canonical_map() -> dict:
    if not MAP_PATH.exists():
        print(f"❌ {MAP_PATH} not found. Run meta/scripts/generate-canonical-map.py first.", file=sys.stderr)
        sys.exit(2)
    data = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    # build lookup: slug → {name, path}
    return data


def build_name_lookup(can_map: dict) -> dict[str, str]:
    """name → relative path for canonical pages. Only entries with actual paths."""
    out = {}
    for slug, info in can_map.items():
        if info.get("path"):
            out[info["name"].lower()] = info["path"]
    return out


def find_files(directory: Path) -> list[Path]:
    return sorted(
        f
        for f in directory.rglob("*.md")
        if f.suffix == ".md"
        and not any(f.is_relative_to(p) for p in EXCLUDE_PREFIXES)
        and not f.name.startswith("_")
    )


def find_bare_mentions(text: str, filepath: Path, name_to_path: dict[str, str]) -> list[dict]:
    """Return violations: list of {line, lineno, name, target_path}."""
    violations = []
    lines = text.splitlines()

    in_code_block = False
    for lineno, raw_line in enumerate(lines, start=1):
        line = raw_line.strip()
        if not line:
            continue

        # ── track fenced code block state ──
        if line.startswith("```"):
            in_code_block = not in_code_block
            continue

        if in_code_block:
            continue

        # ── skip lines that already have a markdown link ──
        if "[" in line:
            continue

        # ── skip table rows (pipe-delimited) ──
        if "|" in line:
            continue

        # ── skip headings ──
        if line.startswith("#"):
            continue

        # ── skip integration-list bullets (bold + colon, optional list prefix) ──
        if re.match(r'^[-*]\s+\*{1,2}[^*]+\*{1,2}\s*:', line):
            continue

        # ── skip hyphenated adjectives like 'OpenAI-совместимый', 'OpenAI-first' ──
        # These are descriptor compounds, not bare mentions

        # ── skip frontmatter fields with URLs ──
        if line.lower().startswith(("url:", "tags:", "title:", "added:", "status:", "category:")):
            continue

        # ── skip lines with inline-code ──
        if "`" in line:
            # Check if the bare mention is inside backticks
            # Simple check: if the whole name is inside backticks, skip
            # More robust: strip inline code segments and only check the rest
            code_spans = re.findall(r"`([^`]*)`", line)
            clean_line = line
            for span in code_spans:
                clean_line = clean_line.replace(f"`{span}`", "")
            # re-check with clean line
            line_to_check = clean_line
        else:
            line_to_check = line

        # ── try each technology name ──
        for name_lower, target_path in name_to_path.items():
            # Skip if the target is the same file (can't link to self in a wiki way)
            if filepath.samefile(ROOT / target_path):
                continue

            name_title = next(
                info["name"]
                for info in load_canonical_map().values()
                if info["name"].lower() == name_lower
            )

            # Skip ambiguous short words unless they appear as whole words
            if name_lower in AMBIGUOUS:
                # BGE must be "BGE " or "BGE)" etc — whole word
                if not re.search(rf'\b{re.escape(name_title)}\b', line_to_check):
                    continue
            # ── URL-path false-positive ──
            if re.search(
                r'[a-zA-Z0-9-]+\.[a-zA-Z]{2,}/[a-zA-Z/]*' + re.escape(name_title),
                line_to_check,
            ):
                continue

            # ── "Opus" as common word ──
            if name_lower == "opus" and "claude" not in line_to_check.lower():
                continue

            if name_lower in line_to_check.lower():
                violations.append({
                    "line": lineno,
                    "text": raw_line.rstrip(),
                    "name": name_title,
                    "target": target_path,
                })

    # Deduplicate: same line + same name only once
    seen = set()
    deduped = []
    for v in violations:
        key = (v["line"], v["name"])
        if key not in seen:
            seen.add(key)
            deduped.append(v)
    return deduped


def main():
    can_map = load_canonical_map()
    name_to_path = build_name_lookup(can_map)

    all_violations = []
    for scan_dir in SCAN_DIRS:
        if not scan_dir.exists():
            continue
        for fpath in find_files(scan_dir):
            text = fpath.read_text(encoding="utf-8")
            violations = find_bare_mentions(text, fpath, name_to_path)
            for v in violations:
                all_violations.append({
                    "file": str(fpath.relative_to(ROOT)),
                    "line": v["line"],
                    "text": v["text"],
                    "name": v["name"],
                    "target": v["target"],
                })

    if not all_violations:
        print("✅ No bare mentions found — all technologies properly linked.")
        sys.exit(0)

    print(f"❌ {len(all_violations)} bare mention(s) found (add wiki-link to canonical page):\n")
    for v in all_violations:
        print(f"  {v['file']}:{v['line']}")
        print(f"    mention: '{v['name']}'  →  should link to {v['target']}")
        print(f"    text:    {v['text'][:120]}")
        print()

    sys.exit(1)


if __name__ == "__main__":
    main()
